### PR TITLE
Add travis closes #20

### LINKED ISSUE #20: Add Travis CI
We should know if pull requests passes the `gulp style-guide` task.

### PR DESCRIPTION
**Pull request by felquis**

### CODE REVIEW

**Comment by felquis** [comment]
@matheusrocha89 could you help me with this?

**Comment by matheusrocha89** [comment]
I think I can. What tasks do you want the Travis CI to run?

**Comment by felquis** [comment]
Check out issue #20 and the current `.travis.yml`

**Comment by felquis** [comment]
Push commits to `addTravis` pls

**Comment by felquis** [comment]
É tetra https://www.youtube.com/watch?v=9ovm-TifjV8

**Comment by giorgiofellipe** [comment]
boa :+1:

**Comment by matheusrocha89** [comment]
hahahahahaha É TETRAAAAAAAAAA!!!

**Comment by felquis** [comment]
I'll check Travis logs, wait a minute :)

**Comment by matheusrocha89** [comment]
I think we can remove the before_install taks on travis.yml, because it will install locally the gulp with npm install by default

**Comment by felquis** [comment]
It'll install locally to use with `require('gulp')`, does travis CI understand the local package as a CLI command?

Well, commit this test and lets see the results, i'll squash these commits before merge.

**Comment by matheusrocha89** [comment]
É PEEENNNTTTTTAAAAAAAA!!!! Can't find a short video about it.

**Comment by felquis** [comment]
@matheusrocha89 So, it worked fine right? Can I merge it now or you'll work on something else?

**Comment by matheusrocha89** [comment]
Yes, you can merge :+1:

**Comment by felquis** [comment]
@matheusrocha89 thanks man :D

**Pull request closed without merging**
